#!/usr/bin/env python3
"""
bf16_algebraic_bridge.py

Algebraic bf16 (uint64 storage) → float64 conversion.
No bit shifts, no reinterpret casts. Pure arithmetic only.

Mirrors the approach from klang's ArithmeticBitwiseOps:
  - right_shift(value, bits) → value // 2^bits
  - mask(value, n_bits)      → value % 2^n_bits

The IEEE 754 bf16 format: 1 sign | 8 exponent | 7 fraction, bias=127
Stored as a 16-bit uint inside a uint64 atom.

VERIFIED: Bit-exact across all 65,536 bf16 values against struct reinterpret.

Core formula:
    fraction = raw % 128
    exponent = (raw // 128) % 256
    sign     = raw // 32768
    result   = (-1)^sign × 2^(exponent - 127) × (1 + fraction/128)

Subnormal: (-1)^sign × 2^(-126) × (fraction / 128)
Special:   exponent=255 → ±inf (frac=0) or NaN (frac≠0)

Generated by Claude (Cowork) for Sydney Bach / The Solace Project.
Intended as a reference for porting into klang Kotlin (ArithmeticBitwiseOps + CBF16).
"""

import struct
import math


# ---------- Arithmetic primitives (no bitwise ops) ----------

def arith_right_shift(value: int, bits: int) -> int:
    """value // 2^bits — equivalent to value >>> bits"""
    if bits <= 0:
        return value
    divisor = 1
    for _ in range(bits):
        divisor *= 2
    return value // divisor


def arith_mask(value: int, n_bits: int) -> int:
    """value % 2^n_bits — equivalent to value & ((1 << n_bits) - 1)"""
    modulus = 1
    for _ in range(n_bits):
        modulus *= 2
    return value % modulus


def pow2(n: int) -> float:
    """2.0^n via repeated multiplication (works for negative n too)"""
    if n == 0:
        return 1.0
    if n > 0:
        r = 1.0
        for _ in range(n):
            r *= 2.0
        return r
    else:
        r = 1.0
        for _ in range(-n):
            r /= 2.0
        return r


# ---------- The algebraic bridge ----------

def bf16_uint_to_float64(raw: int) -> float:
    """
    Convert a bf16 bit pattern (stored as uint64) to float64.
    Pure arithmetic — no shl, shr, &, |, ^, reinterpret_cast.

    bf16 layout (16 bits): [sign:1][exponent:8][fraction:7]

    Decomposition via division and modulo:
      fraction = raw % 128          (lowest 7 bits)
      exponent = (raw // 128) % 256 (next 8 bits)
      sign     = raw // 32768       (top bit of 16)
    """
    fraction = arith_mask(raw, 7)
    exponent = arith_mask(arith_right_shift(raw, 7), 8)
    sign     = arith_right_shift(raw, 15)

    sign_factor = 1.0 if sign == 0 else -1.0

    if exponent == 255:
        if fraction != 0:
            return float('nan')
        else:
            return sign_factor * float('inf')

    if exponent == 0:
        if fraction == 0:
            return sign_factor * 0.0
        return sign_factor * pow2(-126) * (fraction / 128.0)

    return sign_factor * pow2(exponent - 127) * (1.0 + fraction / 128.0)


# ---------- Exhaustive verification ----------

def verify_all():
    """Verify against struct reinterpret for all 65536 bf16 values."""
    mismatches = 0
    for raw in range(65536):
        f32_bits = raw << 16
        ref = struct.unpack('>f', struct.pack('>I', f32_bits))[0]
        alg = bf16_uint_to_float64(raw)
        if math.isnan(ref) and math.isnan(alg):
            continue
        if ref != alg:
            mismatches += 1
            print(f"  MISMATCH raw={raw}: ref={ref}, alg={alg}")
    print(f"Tested 65536 values, mismatches: {mismatches}")
    return mismatches == 0


if __name__ == "__main__":
    print("Verifying bf16 algebraic bridge (all 65536 values)...")
    ok = verify_all()
    print("PASS" if ok else "FAIL")
